"""
change notification status enum

Revision ID: 1a13b2508355
Revises: a9dbf1469664
Create Date: 2025-12-23 14:54:28.496520
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa  # noqa: F401
from alembic_postgresql_enum import TableReference


revision: str = "1a13b2508355"
down_revision: Union[str, Sequence[str], None] = "a9dbf1469664"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="notificationstatus",
        new_values=["PENDING", "SENT", "FAILED"],
        affected_columns=[
            TableReference(table_schema="public", table_name="notification_delivery", column_name="status")
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.sync_enum_values(
        enum_schema="public",
        enum_name="notificationstatus",
        new_values=["PENDING", "SENT", "FAILED", "READ"],
        affected_columns=[
            TableReference(table_schema="public", table_name="notification_delivery", column_name="status")
        ],
        enum_values_to_rename=[],
    )
    # ### end Alembic commands ###
