"""
audit log model

Revision ID: 287a9cf85d43
Revises: 8fe065d4a4de
Create Date: 2025-12-22 11:51:22.206460
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "287a9cf85d43"
down_revision: Union[str, Sequence[str], None] = "8fe065d4a4de"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("notification_delivery", "id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)
    op.alter_column(
        "notification_delivery", "notification_id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False
    )
    op.alter_column("notifications", "id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)
    op.alter_column("notifications", "user_id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)
    op.alter_column("users", "id", existing_type=sa.NUMERIC(), type_=sa.UUID(), existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)
    op.alter_column("notifications", "user_id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)
    op.alter_column("notifications", "id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)
    op.alter_column(
        "notification_delivery", "notification_id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False
    )
    op.alter_column("notification_delivery", "id", existing_type=sa.UUID(), type_=sa.NUMERIC(), existing_nullable=False)
    # ### end Alembic commands ###
