"""
add notifications tables

Revision ID: 9d6cf2dfa61b
Revises: c759d7fb8332
Create Date: 2025-12-16 17:16:00.649981
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "9d6cf2dfa61b"
down_revision: Union[str, Sequence[str], None] = "c759d7fb8332"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "notifications",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("type", sa.Enum("CUSTOM", "WELCOME", name="notificationtype"), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "notification_delivery",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("notification_id", sa.UUID(), nullable=False),
        sa.Column("channel", sa.Enum("EMAIL", "SMS", "INAPP", name="notificationchannel"), nullable=False),
        sa.Column("recipient", sa.String(), nullable=False),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("body", sa.String(), nullable=False),
        sa.Column("status", sa.Enum("PENDING", "SENT", "FAILED", "READ", name="notificationstatus"), nullable=False),
        sa.Column("failure_error_message", sa.String(), nullable=True),
        sa.Column("provider_message_ref", sa.String(), nullable=True),
        sa.Column("sent_at", sa.DateTime(), nullable=True),
        sa.Column("read_at", sa.DateTime(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["notification_id"], ["notifications.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("notification_delivery")
    op.drop_table("notifications")
    # ### end Alembic commands ###
