"""
describe change

Revision ID: c934278fd941
Revises: c759d7fb8332
Create Date: 2025-12-15 16:50:41.805905
"""

from typing import Sequence, Union


revision: str = "c934278fd941"
down_revision: Union[str, Sequence[str], None] = "c759d7fb8332"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
